USE game_dev_portfolio;

CREATE TABLE landing_content (
  section_key VARCHAR(40) PRIMARY KEY,
  content_json JSON NOT NULL,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;
